// Generated by scripts/import-shoe-fits.py; register only validated local assets.
export const SHOE_FITS = [
  {
    "lookId": "xuanling-golden-crown",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/xuanling-golden-crown/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/xuanling-golden-crown/black-pointed-heels/rig.json"
  },
  {
    "lookId": "xuanling-golden-crown",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/xuanling-golden-crown/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/xuanling-golden-crown/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "ruby-white-bikini",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/ruby-white-bikini/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/ruby-white-bikini/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "wuduohui-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/wuduohui-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/wuduohui-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "wuduohui-white-bikini",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/wuduohui-white-bikini/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/wuduohui-white-bikini/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "medusa-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/medusa-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/medusa-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "linwei-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/linwei-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/linwei-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "linwei-white-bikini",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/linwei-white-bikini/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/linwei-white-bikini/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "discipline-lead-noir",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/discipline-lead-noir/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/discipline-lead-noir/black-pointed-heels/rig.json"
  },
  {
    "lookId": "discipline-lead-noir",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/discipline-lead-noir/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/discipline-lead-noir/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "linwei-ivory-wrap",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/linwei-ivory-wrap/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/linwei-ivory-wrap/black-pointed-heels/rig.json"
  },
  {
    "lookId": "noir-evening",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/noir-evening/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/noir-evening/black-pointed-heels/rig.json"
  },
  {
    "lookId": "linwei-ivory-wrap",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/linwei-ivory-wrap/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/linwei-ivory-wrap/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "noir-evening",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/noir-evening/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/noir-evening/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "linwei-red-sole",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/linwei-red-sole/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/linwei-red-sole/black-pointed-heels/rig.json"
  },
  {
    "lookId": "noir-office",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/noir-office/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/noir-office/black-pointed-heels/rig.json"
  },
  {
    "lookId": "linwei-red-sole",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/linwei-red-sole/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/linwei-red-sole/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "noir-office",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/noir-office/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/noir-office/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "wuduohui-plaid-agent",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/wuduohui-plaid-agent/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/wuduohui-plaid-agent/black-pointed-heels/rig.json"
  },
  {
    "lookId": "ruby-velvet",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/ruby-velvet/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/ruby-velvet/black-pointed-heels/rig.json"
  },
  {
    "lookId": "wuduohui-plaid-agent",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/wuduohui-plaid-agent/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/wuduohui-plaid-agent/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "ruby-velvet",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/ruby-velvet/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/ruby-velvet/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "ruby-date",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/ruby-date/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/ruby-date/black-pointed-heels/rig.json"
  },
  {
    "lookId": "ruby-date",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/ruby-date/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/ruby-date/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "silver-leather",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/silver-leather/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/silver-leather/black-pointed-heels/rig.json"
  },
  {
    "lookId": "silver-leather",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/silver-leather/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/silver-leather/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "silver-knit",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/silver-knit/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/silver-knit/black-pointed-heels/rig.json"
  },
  {
    "lookId": "sakura-cafe",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/sakura-cafe/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/sakura-cafe/black-pointed-heels/rig.json"
  },
  {
    "lookId": "yuki-snow",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/yuki-snow/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/yuki-snow/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "silver-knit",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/silver-knit/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/silver-knit/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "zhixia-qipao",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/zhixia-qipao/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/zhixia-qipao/black-pointed-heels/rig.json"
  },
  {
    "lookId": "sakura-cafe",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/sakura-cafe/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/sakura-cafe/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "zhixia-qipao",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/zhixia-qipao/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/zhixia-qipao/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "zhixia-city",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/zhixia-city/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/zhixia-city/black-pointed-heels/rig.json"
  },
  {
    "lookId": "sakura-kimono",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/sakura-kimono/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/sakura-kimono/black-pointed-heels/rig.json"
  },
  {
    "lookId": "sakura-kimono",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/sakura-kimono/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/sakura-kimono/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "zhixia-city",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/zhixia-city/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/zhixia-city/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "yuki-lolita",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/yuki-lolita/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/yuki-lolita/black-pointed-heels/rig.json"
  },
  {
    "lookId": "elise-paris",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/elise-paris/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/elise-paris/black-pointed-heels/rig.json"
  },
  {
    "lookId": "lingyue-hanfu",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/lingyue-hanfu/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/lingyue-hanfu/black-pointed-heels/rig.json"
  },
  {
    "lookId": "elise-paris",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/elise-paris/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/elise-paris/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "yuki-lolita",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/yuki-lolita/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/yuki-lolita/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "lingyue-hanfu",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/lingyue-hanfu/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/lingyue-hanfu/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "yuki-snow",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/yuki-snow/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/yuki-snow/black-pointed-heels/rig.json"
  },
  {
    "lookId": "lingyue-moon",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/lingyue-moon/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/lingyue-moon/black-pointed-heels/rig.json"
  },
  {
    "lookId": "elise-gala",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/elise-gala/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/elise-gala/black-pointed-heels/rig.json"
  },
  {
    "lookId": "mia-denim",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/mia-denim/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/mia-denim/black-pointed-heels/rig.json"
  },
  {
    "lookId": "mia-street",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/mia-street/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/mia-street/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "elise-gala",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/elise-gala/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/elise-gala/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "mia-denim",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/mia-denim/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/mia-denim/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "lingyue-moon",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/lingyue-moon/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/lingyue-moon/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "discipline-lead-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/discipline-lead-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/discipline-lead-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "discipline-lead-white-bikini",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/discipline-lead-white-bikini/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/discipline-lead-white-bikini/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "sakura-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/sakura-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/sakura-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "zhixia-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/zhixia-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/zhixia-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "mia-white-bikini",
    "itemId": "black-pointed-heels",
    "asset": "/wardrobe/fits/mia-white-bikini/black-pointed-heels/character.png",
    "rig": "/wardrobe/fits/mia-white-bikini/black-pointed-heels/rig.json"
  },
  {
    "lookId": "zhixia-white-bikini",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/zhixia-white-bikini/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/zhixia-white-bikini/ivory-soft-slippers/rig.json"
  },
  {
    "lookId": "mia-white-bikini",
    "itemId": "ivory-soft-slippers",
    "asset": "/wardrobe/fits/mia-white-bikini/ivory-soft-slippers/character.png",
    "rig": "/wardrobe/fits/mia-white-bikini/ivory-soft-slippers/rig.json"
  }
];
export const SHOE_FIT_ISSUES = [
  {
    "lookId": "yelan-white-bikini",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "medusa-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "shuanghua-white-bikini",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "yelan-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "shuanghua-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "mia-street",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "lingyue-white-bikini",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "sakura-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "lingyue-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "yuki-white-bikini",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "elise-white-bikini",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "yuki-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "elise-white-bikini",
    "itemId": "ivory-soft-slippers",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  },
  {
    "lookId": "ruby-white-bikini",
    "itemId": "black-pointed-heels",
    "message": "该组合生成未通过审核，未加入可穿库存。"
  }
];
