"""Import approved ImageGen assets byte-for-byte and calibrate their own rigs.

Input is docs/shoe-fit-generation.json. This never edits image pixels or sources.
Vision landmarks and sampled colors calibrate the new texture, not another model.
"""
import json
import shutil
import subprocess
from pathlib import Path
from statistics import median
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
manifest = json.loads((ROOT / "docs/shoe-fit-generation.json").read_text())
entries = manifest["generated"]
detected = subprocess.run(["swift", str(ROOT / "scripts/face-landmarks.swift"), "--full-body",
                          *[entry["generatedSource"] for entry in entries]],
                         check=True, capture_output=True, text=True)
landmarks = {entry["path"]: entry for entry in map(json.loads, detected.stdout.splitlines())}
ready = [["xuanling-golden-crown", "black-pointed-heels"],
         ["xuanling-golden-crown", "ivory-soft-slippers"],
         ["ruby-white-bikini", "ivory-soft-slippers"]]
issues = [{"lookId": entry["lookId"], "itemId": entry["itemId"],
           "message": "该组合生成未通过审核，未加入可穿库存。"} for entry in manifest["rejected"]]
for entry in entries:
    source = Path(entry["generatedSource"])
    mark = landmarks[str(source)]
    target = ROOT / "public/wardrobe/fits" / entry["lookId"] / entry["itemId"]
    with Image.open(source) as image:
        if image.mode != "RGBA" or image.size != (1024, 1536):
            issues.append({"lookId": entry["lookId"], "itemId": entry["itemId"], "message": "素材尺寸或透明通道检验未通过。"})
            continue
        if "error" in mark or len(mark["eyes"]) != 2 or not all("x" in eye for eye in mark["eyes"]):
            issues.append({"lookId": entry["lookId"], "itemId": entry["itemId"], "message": "面部校准未通过，未加入可穿库存。"})
            print("UNCALIBRATED", entry["lookId"], entry["itemId"], mark)
            continue
        pixels = image.load()
        def sample(x, y, radius=3):
            points = [pixels[max(0,min(1023,round(x*1024)+dx)),max(0,min(1535,round(y*1536)+dy))]
                      for dx in range(-radius,radius+1) for dy in range(-radius,radius+1)]
            return [round(median(p[i] for p in points)/255,4) for i in range(3)]
        base = json.loads((ROOT / "public/looks" / entry["lookId"] / "rig.json").read_text())
        face = mark["face"]
        face_y = (face["top"] + face["bottom"]) / 2
        if (abs(face_y - base["head"]["y"]) > 0.15 or
                mark["mouth"].get("y", 0) <= max(eye["y"] for eye in mark["eyes"])):
            issues.append({"lookId": entry["lookId"], "itemId": entry["itemId"], "message": "面部校准检验未通过，未加入可穿库存。"})
            print("UNCALIBRATED", entry["lookId"], entry["itemId"], mark)
            continue
        eyes = []
        for eye in mark["eyes"]:
            eye = dict(eye)
            eye["rx"] *= 1.65
            eye["ry"] = max(eye["ry"]*1.55,0.0037)
            eye["skin"] = sample(eye["x"],eye["y"]+eye["ry"]*2.3)
            eye["lid"] = [0.19,0.105,0.12]
            eyes.append(eye)
        mouth = dict(mark["mouth"])
        mouth["skin"] = sample(mouth["x"],mouth["y"]+mouth["ry"]*2.1)
        mouth["lip"] = sample(mouth["x"],mouth["y"]+mouth["ry"]*0.65,1)
        mouth["inner"] = [0.22,0.05,0.075]
        mouth["rx"] *= 1.02
        mouth["ry"] = max(mouth["ry"],0.0047)
        bounds = image.getchannel("A").point(lambda v:255 if v>127 else 0).getbbox()
        rig = {"armMobility":base.get("armMobility",0),
               "head":{"x":(face["left"]+face["right"])/2,"y":(face["top"]+face["bottom"])/2,
                       "neckY":face["bottom"]+0.022,"radiusX":0.15,"radiusY":0.085},
               "eyes":eyes,"mouth":mouth,"shoulders":base["shoulders"],
               "bounds":dict(zip(["left","top","right","bottom"],[bounds[0]/1024,bounds[1]/1536,bounds[2]/1024,bounds[3]/1536]))}
    target.mkdir(parents=True,exist_ok=True)
    shutil.copyfile(source,target / "character.png")
    (target / "rig.json").write_text(json.dumps(rig,ensure_ascii=False,indent=2)+"\n")
    (target / "provenance.json").write_text(json.dumps({**entry,"provider":"builtin-imagegen","faceConfidence":mark["confidence"],"pixelProcessing":"none"},ensure_ascii=False,indent=2)+"\n")
    ready.append([entry["lookId"],entry["itemId"]])
    print("READY",entry["lookId"],entry["itemId"])

fits = [{"lookId":look,"itemId":item,"asset":f"/wardrobe/fits/{look}/{item}/character.png", "rig":f"/wardrobe/fits/{look}/{item}/rig.json"} for look,item in ready]
(ROOT / "server/wardrobe-fits.mjs").write_text("// Generated by scripts/import-shoe-fits.py; register only validated local assets.\nexport const SHOE_FITS = "+json.dumps(fits,ensure_ascii=False,indent=2)+";\nexport const SHOE_FIT_ISSUES = "+json.dumps(issues,ensure_ascii=False,indent=2)+";\n")
print("TOTAL",len(fits),"ready;",len(issues),"issues")
