export {
  BACKGROUNDS,
  CHARACTERS,
  CURATED_STYLE_RECIPES,
  GARMENT_SLOT_IDS,
  OUTFIT_VARIANTS,
  getCharacter,
  getCharacterForLook,
  getCharacterLooks,
  getDefaultBackgroundId,
  getOutfitVariant,
  getVariantsBySlot,
  isBackgroundId,
  resolveEmptyOutfit,
} from "../server/wardrobe.mjs";
